-- =========================================================
-- Source: create_user_table.sql
-- =========================================================
CREATE TABLE roles (
    id BIGSERIAL PRIMARY KEY,

    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles(name)
VALUES
('ROLE_SUPER_ADMIN'),
('ROLE_ADMIN');

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    email VARCHAR(255) UNIQUE NOT NULL,

    username VARCHAR(100) UNIQUE NOT NULL,

    password_hash VARCHAR(255) NOT NULL,

    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    role_id BIGINT NOT NULL,
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_role
        FOREIGN KEY(role_id)
        REFERENCES roles(id)
);

CREATE TABLE refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL,

    token_hash VARCHAR(255) NOT NULL UNIQUE,

    expires_at TIMESTAMP NOT NULL,

    revoked BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notification_categories
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL
);

INSERT INTO notification_categories (code, title)
VALUES
    ('ANOMALY_DETECTED', 'Зафиксировано аномальное значение'),
    ('ERROR_FORECAST', 'Спрогнозировано большое количество ошибок в следующем часу'),
    ('ERROR_LOG_RECEIVED', 'Пришел лог с ошибкой')
ON CONFLICT (code) DO UPDATE
    SET title = EXCLUDED.title;

CREATE TABLE IF NOT EXISTS user_notification_settings
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    category_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_notification_settings_user FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_notification_settings_category FOREIGN KEY(category_id)
        REFERENCES notification_categories(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_user_notification_settings UNIQUE(user_id, category_id)
);

CREATE TABLE IF NOT EXISTS notification_outbox
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT fk_notification_outbox_category FOREIGN KEY(category_id)
        REFERENCES notification_categories(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_status_next_attempt
    ON notification_outbox(status, next_attempt_at);


-- =========================================================
-- Source: Create_log_db.sql
-- =========================================================
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.microservices
(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    microservice_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.action_methods
(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	microservice_id bigint NOT NULL,
    action_eng VARCHAR(100) NOT NULL,
    action_rus VARCHAR(100) NOT NULL,
    CONSTRAINT uq_action_methods_microservice_action UNIQUE (microservice_id, action_eng)
);

ALTER TABLE IF EXISTS public.action_methods
    ADD CONSTRAINT fk_action_methods_microservice FOREIGN KEY (microservice_id)
    REFERENCES public.microservices (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS public.request_status
(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    request_status_code integer NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.log_types
(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    log_type_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.logs
(
    id bigint GENERATED ALWAYS AS IDENTITY,
	correlation_id UUID NOT NULL,
    microservice_id bigint NOT NULL,
    action_method_id bigint NOT NULL,
	username VARCHAR(200),
    request_status_id bigint,
    log_date timestamp with time zone NOT NULL,
    log_type_id bigint,
    log_data jsonb NOT NULL,
    duration integer,
    PRIMARY KEY (id, log_date)
) PARTITION BY RANGE (log_date);

ALTER TABLE IF EXISTS public.logs
    ADD CONSTRAINT fk_logs_microservice FOREIGN KEY (microservice_id)
    REFERENCES public.microservices (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.logs
    ADD CONSTRAINT fk_logs_action_method FOREIGN KEY (action_method_id)
    REFERENCES public.action_methods (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.logs
    ADD CONSTRAINT fk_logs_request_status FOREIGN KEY (request_status_id)
    REFERENCES public.request_status (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.logs
    ADD CONSTRAINT fk_logs_log_type FOREIGN KEY (log_type_id)
    REFERENCES public.log_types (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;

--Индексы
CREATE INDEX idx_correlation_id ON logs(correlation_id);
CREATE INDEX idx_logs_microservice ON logs(microservice_id);
CREATE INDEX idx_logs_action_method ON logs(action_method_id);
CREATE INDEX idx_logs_status ON logs(request_status_id);
CREATE INDEX idx_logs_date ON logs(log_date);
CREATE INDEX idx_logs_type ON logs(log_type_id);
CREATE INDEX idx_duration ON logs(duration);
CREATE INDEX idx_username ON logs(username);

--GIN индексы
CREATE INDEX idx_logs_jsonb ON logs USING GIN (log_data);

--Запасная партиция
CREATE TABLE IF NOT EXISTS public.logs_default
PARTITION OF public.logs DEFAULT;

END;


-- =========================================================
-- Source: alter_action_methods_unique_for_ingest.sql
-- =========================================================
ALTER TABLE IF EXISTS public.action_methods
    DROP CONSTRAINT IF EXISTS action_methods_action_eng_key;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_action_methods_microservice_action'
          AND conrelid = 'public.action_methods'::regclass
    ) THEN
        ALTER TABLE public.action_methods
            ADD CONSTRAINT uq_action_methods_microservice_action
            UNIQUE (microservice_id, action_eng);
    END IF;
END;
$$;


